-- 创建数据库（若尚未创建）
CREATE DATABASE IF NOT EXISTS todo_db
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE todo_db;

-- Todo 表：id 自增，重启后数据仍保留
CREATE TABLE IF NOT EXISTS todos (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    priority INT NOT NULL DEFAULT 2,
    due_date DATE DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_due_date (due_date)
) ENGINE=InnoDB;
